### ISSUE TITLE
Copy-pasting from Excel doesn't work in OSX

### ISSUE THREAD

**Issue by smathot** [smathot/python-qdatamatrix#3] opened 2016-09-26 17:42 UTC
According to the post below, if you copy paste from Excel to QDataMatrix, all cells are pasted into one cell. This happens only on OSX.
- http://forum.cogsci.nl/index.php?p=/discussion/comment/8404/#Comment_8404

**Comment by jsbenjamins** [comment] 2016-09-30 13:06
I've been diving into the issue myself as well and think I've narrowed it down to a problem with carriage returns and line feeds. When I copy multiple lines from excel it separates lines by using a carriage return, where OpenSesame expects a line feed. 

When I make the excel table into a tab delimited text file with line feeds at every line, copy-paste works again. 

**This is a more general issue with copy-paste though:** if I have code (in let's say manual for students) which **has** line feeds, they become carriage returns when pasting in for example a form_base.

**Comment by smathot** [comment] 2016-09-30 16:21
Thanks for this. It's most likely related to the different ways in which different operating systems indicate newlines. qdatamatrix now assumes the unix-style `\n`. If you edit:
- https://github.com/smathot/python-qdatamatrix/blob/master/qdatamatrix/_qspreadsheet.py#L401

And change the `_paste()` function to:

``` .python
    @undoable
    def _paste(self):

        """
        desc:
            Pastes the current clipboard contents onto the DataFrame.
        """

        txt = self._clipboard.mimeData().text()
        # This is new
        import os
        txt = txt.replace(os.linesep, u'\n')
        # Until here
        rows = txt.split(u'\n')
        for i, row in enumerate(rows):
            cells = row.split(u'\t')
            for j, cell in enumerate(cells):
                if cell != EMPTY_STR:
                    self._setcell(self.currentRow()+i, self.currentColumn()+j,
                        cell)
```

Does that solve the issue?

Also, could you open a similar issue on the OpenSesame repository, with a clear description of what exactly goes wrong there? The underlying issue is probably the same, but the fix will be different.

**Comment by smathot** [comment] 2016-10-07 10:34
Have you had a chance to look at this?

**Comment by jsbenjamins** [comment] 2016-10-07 12:52
No, I have not had time to have a look at it, as I am now training my teachers to use the current OpenSesame version so they can teach 400+ students to use OpenSesame in a month's time. I currently don't have any development or tinker time, since it would require creating a custom OpenSesame that I would need to test before unleashing it on said students. So for this year, we'll work with a workaround for this copy-paste issue in our course and by the end of the year I might have time to look into it.

**Comment by smathot** [comment] 2016-10-07 13:44
@dschreij Could you give it a spin on your Mac if you have a spare moment?

**Comment by smathot** [comment] 2017-01-09 09:12
This related to smathot/QProgEdit#19. See also:

- http://forum.cogsci.nl/index.php?p=/discussion/2592/

In general, copy-pasting to editor components (QProgEdit) and tables (QDataMatrix) doesn't work on Mac OS. At least part of the problem seems to be incorrect line-ending conversions.

**Comment by dschreij** [comment] 2017-01-28 15:42
Alright, I tried this out, and now rows are pasted into columns. If I paste

~~~
een	twee	drie
1	9	9
2	9	18
3	9	27
4	9	36
5	9	45
6	9	54
7	9	63
8	9	72
9	9	81
~~~

from Excel into a DataMatrix, I get:

![screenshot 2017-01-28 11 41 30](https://cloud.githubusercontent.com/assets/689044/22397740/c538ed7a-e54e-11e6-9082-6244fbb74d03.png)

At least, things do not end up in one single column anymore.

**Comment by dschreij** [comment] 2017-01-28 17:45
I tinkered a bit further and hopefully https://github.com/smathot/python-qdatamatrix/pull/4 fixes this problem. It does so on my Mac at least, but it would be preferable to have more tests. @jsbenjamins, do you have the time to give it a little test?

**Comment by smathot** [comment] 2017-01-30 13:09
Thanks @dschreij. Question: were you able to replicate the problem to begin with? I wanted to test it on a student's Mac (running Mac OS Sierra), but copy-pasting worked fine to begin with.

**Comment by dschreij** [comment] 2017-01-30 13:56
I wasn't able to *exactly* reproduce it (as in that everything was pasted into a single cell), but I still had the problem that everything was pasted in the first row (see screenshot above). This difference may be due to the change you already committed and mentioned in https://github.com/smathot/python-qdatamatrix/issues/3#issuecomment-250788296.

I don't know why copy-pasting works correctly for you without the patch. This may be due to the version of Excel you use (I have 15.30), of its internationalisation settings (although I think that should't matter for newlines).

With QProgEdit I had no problems whatsoever, but that was because I didn't really have a clear description of steps to reproduce the problem.

**Comment by smathot** [comment] 2017-01-30 14:35
I suspect it's resolved, but just to check: If you copy paste multi-line text into either `QProgEdit` or `QDataMatrix`, and you then look at the item script, is everything syntactically ok there? For example, what happened before (in `QProgEdit`) was that the OpenSesame script looked like:

~~~
set my_variable "Line 1
Line 2"
~~~

This is syntactically invalid, resulting from OpenSesame's failure to recognize the line breaks. Instead, it should look like:

~~~
__my_variable__
Line 1
Line 2
__end__
~~~

If the script looks ok for you, then I think we have this bug squashed, and we can go ahead and release 3.1.5. I'll send you a complete list of to-be-updated packages and a handful of new dependencies later.

And thanks! :+1:

**Comment by dschreij** [comment] 2017-01-30 17:42
If I create a Word document containing

~~~
Line 1
Line 2
Line 3
~~~

and paste this into QProgEdit (or inline_script item), I see this in the OpenSesame code:

~~~
set description "Executes Python code"
set _run ""
___prepare__
Line 1
Line 2
Line 3
__end__
~~~

If I post this same content to QDataMatrix (or a OpenSesame loop item) I see it all pasted in the first column over 3 rows (as you'd expect).

Pasting this content from Word into QDataMatrix
~~~
Line 1	Next col
Line 2	Next col
Line 3	Next col
~~~
(where `Line X` and `next col` are separated by a tab) puts every Line X and Next col in its own cell (so it only splits over tabs and not spaces).

That's all as it should be, isn't it?

**Comment by smathot** [comment] 2017-01-30 17:47
> That's all as it should be, isn't it?

I see the confusion, but the test that I had in mind is this: Paste some multlline code into an `inline_script`. Say this:

~~~ .python
line1 = 1
line2 = 2
~~~

Then you open the script behing the script (you know what I mean). It should look like:

~~~
set description "Executes Python code"
set _run ""
___prepare__
line1 = 1
line2 = 2
__end__
~~~

And *not* like:

~~~
set description "Executes Python code"
set _run ""
set _prepare "line1 = 1
line2 = 2"
~~~

**Comment by dschreij** [comment] 2017-01-30 18:28
That's what I did, didn't I? I wrote three lines in Word (if anything messes up newlines and stuff it's Word, so it seemed like a good source to copy from) and pasted those in an inline_script item. It appeared as the first option, so that's correct.

I tried again with Sublime as the copy source and that also went fine:

~~~python
import os, sys, platform

# THIS HAS TO GO FIRST!
# Support for multiprocessing when packaged
# In OS X the multiprocessing module is horribly broken, but a fixed
# version has been released as the 'billiard' module
if platform.system() == 'Darwin':
	# Use normal multirpocessing module from python 3.4 and on
	if sys.version_info >= (3,4):
		from multiprocessing import freeze_support, set_start_method
		freeze_support()
		set_start_method('spawn')
	else:
		from billiard import freeze_support, forking_enable
		freeze_support()
		forking_enable(0)
else:
	from multiprocessing import freeze_support
	freeze_support()
~~~

appears as

~~~
set description "Executes Python code"
set _run ""
___prepare__
import os, sys, platform

# THIS HAS TO GO FIRST!
# Support for multiprocessing when packaged
# In OS X the multiprocessing module is horribly broken, but a fixed
# version has been released as the 'billiard' module
if platform.system() == 'Darwin':
	# Use normal multiprocessing module from python 3.4 and on
	if sys.version_info >= (3,4):
		from multiprocessing import freeze_support, set_start_method
		freeze_support()
		set_start_method('spawn')
	else:
		from billiard import freeze_support, forking_enable
		freeze_support()
		forking_enable(0)
else:
	from multiprocessing import freeze_support
	freeze_support()
__end__

~~~

**Closed as completed** 2017-02-02 08:23 UTC
Labels: bug
